# Generated by Django 4.1.3 on 2022-11-01 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cat',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.catagories'),
        ),
    ]
